image: maven:3-jdk-8

stages:
    - compile
    - test

compile:
    script: "mvn compile --batch-mode"
    # only:
       # - master

test:
    stage: test
    script: "mvn test --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true"
    # dependencies: 
        # - compile
