# see: https://gitlab.com/gitlab-com/support-forum/issues/537
before_script: 
    - "apt-get update"
    - "apt-get install -y openjfx"

image: maven:3-jdk-8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

# Not sure if needed as seperate job. KMT sep'19
#build:
#  script: "mvn install -B --fail-at-end -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true"
  
test:
  script: "mvn test -B --fail-at-end -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true"

# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project
